#!/usr/bin/env bash

## Description: Start and prepare for local development.
## Example: ddev arm

set -e

ddev start
ddev auth ssh

echo -e "\n\nOne-time login URL:"
ddev drush uli

say "D dev started" || echo "\a"

